name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t muhammad444/python-auth-app:latest .

      - name: Set up Docker credentials
        run: |
          echo '{"auths": {"https://index.docker.io/v1/": {"auth": "'$(echo -n "muhammad444:dckr_pat_Rt8P_SSPrCh1-RKdnqW2H7XKaSM" | base64 -w 0)'"}}}' > ~/.docker/config.json

      - name: Push to Docker Hub
        run: docker push muhammad444/python-auth-app:latest
